dist: xenial
sudo: required

language: rust
rust:
  - nightly

addons:
  apt:
    update: true
    packages:
      - build-essential
      - libgtk-3-dev
      - libcddb2-dev
      - libcdio-paranoia-dev
      - libiso9660-dev
      - libudf-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libsoup2.4-dev
      - libxtst-dev
      - at-spi2-core
      - openbox
      - libxdo-dev
      - libmount-dev

services:
  - xvfb

env:
  - GTK=3.14

before_script:
  - openbox &

script:
  - cargo build
  - cargo test -- --test-threads 1
