[package]
name = "rthunder"
version = "0.1.0"
authors = ["patrickp89 <patrickpreuss@netherspace.de>"]
edition = "2018"
build = "build.rs"

[dependencies]
gtk = { version = "0.5.0", features = ["v3_12"] }
